### ISSUE TITLE
As a user, i want to register for an account 

### ISSUE THREAD

**Issue by Anusha-Reddy-Lattupally** [linaism/SOEN341#17]
Story description:
Users should be able to to register for a new users account in order to gain access to the platform's functionalities including asking and answering the questions, voting the questions all through Register page interface.

The registration page include fields for inputting the necessary registration information to create an account with this data,
The interface should perform input validation.

The credentials of new user account should be stored securely following proper standards.

Acceptance Test:
- [x] Step 1: The user username is unique.
- [x] Step 2: The password is valid.
- [x] Step 3: A new user can be created and saved.
- [x] Step 4: Being able to login with new credentials.

Story points : 5
Risk: high
Priority: high

**Comment by Anusha-Reddy-Lattupally** [comment]
Acceptance Test:
Step 1:  The user username is unique.
Step 2:  The password is valid.
Step 3: A new user can be created and saved.
Step 4:  Being able to login with new credentials.

**Comment by ani-6292** [comment]
This issue has been resolved
